//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGBIMMunicipalPipeline.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGBIMMunicipalPipeline.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 圆形废水检查井 {
            get {
                object obj = ResourceManager.GetObject("圆形废水检查井", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 圆形污水检查井 {
            get {
                object obj = ResourceManager.GetObject("圆形污水检查井", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 圆形给水检查井 {
            get {
                object obj = ResourceManager.GetObject("圆形给水检查井", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 排水沟 {
            get {
                object obj = ResourceManager.GetObject("排水沟", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 检修井 {
            get {
                object obj = ResourceManager.GetObject("检修井", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;dictionary category=&quot;管点调查表&quot;&gt;
        ///    &lt;key&gt;CODE&lt;/key&gt;
        ///    &lt;value&gt;类型&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管点调查表&quot;&gt;
        ///    &lt;key&gt;EXP_NO&lt;/key&gt;
        ///    &lt;value&gt;物探点号（管点编号）&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管点调查表&quot;&gt;
        ///    &lt;key&gt;X&lt;/key&gt;
        ///    &lt;value&gt;X坐标&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管点调查表&quot;&gt;
        ///    &lt;key&gt;Y&lt;/key&gt;
        ///    &lt;value&gt;Y坐标&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管点调查表&quot;&gt;
        ///    &lt;key&gt;SUR_H&lt;/key&gt;
        ///    &lt;value&gt;地面高程&lt;/value&gt;
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 管点调查表 {
            get {
                return ResourceManager.GetString("管点调查表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;dictionary category=&quot;管线调查表&quot;&gt;
        ///    &lt;key&gt;CODE&lt;/key&gt;
        ///    &lt;value&gt;管线类型&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管线调查表&quot;&gt;
        ///    &lt;key&gt;S_POINT&lt;/key&gt;
        ///    &lt;value&gt;起始点号&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管线调查表&quot;&gt;
        ///    &lt;key&gt;E_POINT&lt;/key&gt;
        ///    &lt;value&gt;终止点号&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管线调查表&quot;&gt;
        ///    &lt;key&gt;S_DEEP&lt;/key&gt;
        ///    &lt;value&gt;起点埋深&lt;/value&gt;
        ///  &lt;/dictionary&gt;
        ///  &lt;dictionary category=&quot;管线调查表&quot;&gt;
        ///    &lt;key&gt;E_DEEP&lt;/key&gt;
        ///    &lt;value&gt;终点埋深&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 管线调查表 {
            get {
                return ResourceManager.GetString("管线调查表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 雨水口 {
            get {
                object obj = ResourceManager.GetObject("雨水口", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 雨水检查井 {
            get {
                object obj = ResourceManager.GetObject("雨水检查井", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
